/** Spot illustrations (public/images/spots/, generated by scripts/generate-spots.mjs) per workshop slug. */
export const WORKSHOP_ICONS: Record<string, string> = {
  'ai-introductie': 'workshop-introductie',
  'bouwen-met-claude-code': 'workshop-bouwweek',
};
export const spot = (name: string) => `/images/spots/${name}.webp`;
