import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';
import node from '@astrojs/node';
import rehypeTableWrap from './src/lib/rehype-table-wrap.mjs';
import redirects from './src/data/redirects.json' with { type: 'json' };

// Dutch-only site (decision D12). Every old demodernenomaden.nl URL, affiliate /go/ link and
// retired page is answered through `redirects` (generated by scripts/cleanup-content.py).
//
// Output is 'server' with the Node adapter, but every page sets `export const prerender = true`,
// so the whole site is still built as static HTML. The only on-demand routes are the redirects,
// which the Node server answers with real 301 responses (in 'static' output they would be
// meta-refresh pages). The old domain itself is redirected by a Cloudflare rule (decision D21),
// so no host check is needed here. Start command: `npm run start` (see railway.json).
export default defineConfig({
  site: 'https://mickyvanzadelhoff.com',
  trailingSlash: 'ignore',
  output: 'server',
  adapter: node({ mode: 'standalone' }),
  // Hosts the Node server may trust for the request URL. Without this Astro 5 falls back to
  // "localhost", and the built-in CSRF check then rejects the intake form's POST in production.
  security: {
    allowedDomains: [
      { hostname: 'mickyvanzadelhoff.com' },
      { hostname: '*.mickyvanzadelhoff.com' },
      { hostname: '*.up.railway.app' },
      { hostname: 'localhost', port: '4321' },
      { hostname: '127.0.0.1', port: '4321' },
    ],
  },
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/go/') && !page.includes('/downloads/'),
    }),
    tailwind(),
  ],
  markdown: { rehypePlugins: [rehypeTableWrap] },
  redirects,
});
