import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';
import redirects from './src/data/redirects.json' with { type: 'json' };

// Dutch-only site (decision D12). Every old demodernenomaden.nl URL, affiliate /go/ link and
// retired page is answered through `redirects` (generated by scripts/cleanup-content.py).
// With the static adapter these are meta-refresh pages; the Node adapter added at launch
// (Phase 6) turns the same table into real 301 responses.
export default defineConfig({
  site: 'https://mickyvanzadelhoff.com',
  trailingSlash: 'ignore',
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/go/') && !page.includes('/downloads/'),
    }),
    tailwind(),
  ],
  redirects,
});
